version: '3.5'

services:

  task-broker:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${BROKER_VHOST}
    ports:
      - "5672:5672"

  task-db:
    image: mongo:latest
    ports:
      - "27017:27017"

  task-server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      BROKER_VHOST: ${BROKER_VHOST}
      DB_HOST: "task-db"
      DB_DATABASE: "task-service"

  task-worker:
    build: ./worker
    environment:
      BROKER_HOST: "task-broker"
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      BROKER_VHOST: ${BROKER_VHOST}
      DB_HOST: "task-db"
      DB_DATABASE: "task-service"
